service: lambda-chatgpt
plugins:
  - serverless-plugin-typescript

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stackName: lambda-chatgpt
  region: eu-west-2
  versionFunctions: false
  deploymentBucket: my-lambda-deployments
  environment:    
functions:
  callchatgpt:
    handler: handler.main
    url: true
    OPENAI_KEY: ${env:OPENAI_KEY}
